language: python
python:
  - 2.7

# do the SQL cakewalk
before_install:
    - echo "deb http://spritelink.github.io/NIPAP/repos/apt stable main extra" | sudo tee /etc/apt/sources.list.d/nipap.list
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y --force-yes nipapd
    - echo "set nipapd/autoconf true" | sudo debconf-communicate
    - echo "set nipapd/startup false" | sudo debconf-communicate
    - sudo dpkg-reconfigure nipapd
    - sudo apt-get install -qq python-pysqlite2 python-twisted-web python-psycopg2 python-ipy python-ldap python-docutils python-tornado

# get the python stuff installed
install:
    - pip install --use-mirrors psycopg2 ipy twisted python-ldap pysqlite pyasn1 Flask-XML-RPC tornado
    - sudo make install
    - sudo cp nipap/nipap.conf.dist /etc/nipap/nipap.conf
    - sudo cp nipap/local_auth.db /etc/nipap/
    - cp nipap-cli/nipaprc ~/.nipaprc

script:
    - cd nipap
    - sudo ./nipapd --no-pid-file
    - cd ../tests
    - nosetests xmlrpc.py
    - nosetests nipaptest.py

notifications:
  irc:
      channels:
           - "irc.freenode.org#NIPAP"
